// Import useState hook from React
// This allows the component to manage internal state (queue numbers)
import { useState } from "react";

// Import Sidebar component for navigation
import Sidebar from "../components/Sidebar";

// Import QueueGen styles
import "./queuegen.css";

// Export QueueGen component
// Receives the authenticated user object and allowed pages
export default function QueueGen({ user, allowedPages = [], onNavigate }) {
  // State to hold the current queue number
  const [queueNumber, setQueueNumber] = useState(0);

  // Function to generate a new queue number
  const generateQueueNumber = () => {
    setQueueNumber(prev => prev + 1);
  };

  // Function to reset queue number
  const resetQueue = () => {
    setQueueNumber(0);
  };

  return (
    <div className="queuegen-main">
      {/* Sidebar Navigation */}
      <Sidebar allowedPages={allowedPages} onNavigate={onNavigate} />

      <div className="queuegen-container">
        <h2>📋 Queue Number Generator</h2>

        {/* Display current queue number */}
        <div className="queue-display">
          <p>Current Number:</p>
          <span className="queue-number">{queueNumber}</span>
        </div>

        {/* Buttons to generate and reset queue */}
        <div className="queue-buttons">
          <button className="btn-generate" onClick={generateQueueNumber}>
            Generate Next Number
          </button>
          <button className="btn-reset" onClick={resetQueue}>
            Reset Queue
          </button>
        </div>

        {/* Display user info at the bottom */}
        <div className="queue-user-info">
          <p>Generated by: <strong>{user?.name || "Guest"}</strong></p>
        </div>
      </div>
    </div>
  );
}
